### PR TITLE
ev3dev: add build tags for compilation on other OS

### LINKED ISSUE #33: Code does not compile on platforms other than Linux
I'm developing code on OS X and the package does not compile locally because of the unix.Poll dependency. This is generally not an issue because of cross compilation, but code completion and other local tools do not work correctly.

There should be a build tag for the code that uses the unix dependency in a separate file, so it has a bogus implementation for other platforms.

I got that working and will push a PR soon.

### PR DESCRIPTION
**Pull request by hlubek**
Closes #33

### CODE REVIEW

File: wait_linux.go [hunk 1]
```diff
@@ -0,0 +1,96 @@
+// +build linux
```
Comment (kortschak) [inline wait_linux.go]: Please add a license header with ©2017.

File: wait_other.go [hunk 2]
```diff
@@ -0,0 +1,14 @@
+// +build !linux
```
Comment (kortschak) [inline wait_other.go]: Please add a license header with ©2017.

File: wait_other.go [hunk 3]
```diff
@@ -0,0 +1,14 @@
...
+
+import (
+	"time"
+
+	"errors"
+)
+
+// Wait is not implemented without a linux OS (needs unix.Poll)
+func Wait(d StaterDevice, mask, want, not MotorState, any bool, timeout time.Duration) (stat MotorState, ok bool, err error) {
+	return stat, false, errors.New("ev3dev: needs unix OS")
```
Comment (kortschak) [inline wait_other.go]: This probably deserves a `panic("ev3dev: needs GOOS=linux").

File: wait_other.go [hunk 4]
```diff
@@ -0,0 +1,14 @@
...
+
+package ev3dev
+
+import (
+	"time"
+
+	"errors"
+)
+
+// Wait is not implemented without a linux OS (needs unix.Poll)
```
Comment (kortschak) [inline wait_other.go]: Please add a full stop.

File: wait_other.go (hunk 3 above)
Comment (kortschak) [inline wait_other.go]: Also probably worth mirroring all the actual documentation here so that godoc works - leave the line that is there at the bottom with a single blank `//` line.

**Comment by hlubek** [comment]
Done. Thx. for the review!

**Comment by kortschak** [comment]
Sorry, I snuck in https://github.com/ev3go/ev3dev/pull/34#discussion_r98173413. Can you do that too (in the first commit)? This will let godoc work properly for you too (I imagine it doesn't work right now - though I can't test that).

**Comment by kortschak** [comment]
Thank you.
