### PR TITLE
ev3dev: fix lego-port caching

### LINKED ISSUE #66: ev3dev: cache mode and device invariant lego-port attributes
This is equivalent to #64.

- [x] `driver` - I believe I have implemented this incorrectly in the current code as it only caches on creation, not on writes to `set_device` @dlech?
- [x] `mode` - cache on writes to `mode`

### PR DESCRIPTION
**Pull request by kortschak**
@dlech Please take a look.

Fixes #66.

### CODE REVIEW

File: lego_port.go [hunk 1]
```diff
@@ -24,8 +24,13 @@ type LegoPort struct {
 	id int
 
 	// Cached values:
+	modes []string
```
Comment (kortschak) [inline lego_port.go]: Confirm that this is not changed by a write to `set_device`?

Comment (dlech) [reply lego_port.go]: Confirmed. Writing to `set_device` will create a new `lego-sensor` device. It does not affect the port state in any way.

**Comment by dlech** [comment]
LGTM
